### ISSUE TITLE
Console log spam

### ISSUE THREAD

**Issue by ZigTheHedge** [AlexIIL/Buildcraft_1.8_Issues#109]
Hi!

Dedicated server, Forge 1722. My log file filled with the following:

```
[08:05:13] [Server thread/ERROR] [FML]: A TileEntity type buildcraft.transport.TileGenericPipe has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.IllegalArgumentException: Empty string not allowed
        at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:22) ~[ea.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:104) ~[dn.class:?]
        at buildcraft.transport.TileGenericPipe.func_145841_b(TileGenericPipe.java:261) ~[TileGenericPipe.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:368) [anj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:165) [anj.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:238) [ld.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:298) [ld.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:904) [le.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:366) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:628) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

Using buildcraft version 9.

**Comment by AlexIIL** [comment]
That’s odd and annoying, but Its happening in my dev environment so I might be able to find out what’s causing this and fix it :)

**Comment by Okimo** [comment]
Erm also that "Hi" Spam is little bit too much ;_;
