### ISSUE TITLE
Find out what is making minecrafts CRASH REPORT classes CRASH

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/Buildcraft_1.8_Issues#42]
It makes something like this:

```
[18:50:56] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
    at net.minecraft.crash.CrashReportCategory.firstTwoElementsOfStackTraceMatch(Unknown Source) ~[CrashReportCategory.class:?]
    at net.minecraft.crash.CrashReport.makeCategoryDepth(Unknown Source) ~[CrashReport.class:?]
    at net.minecraft.world.World.addWorldInfoToCrashReport(Unknown Source) ~[World.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(Unknown Source) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(Unknown Source) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.tick(Unknown Source) ~[IntegratedServer.class:?]
    at net.minecraft.server.MinecraftServer.run(Unknown Source) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

**Comment by iame6162013** [comment]
I got this error when I made a mistake in opengl handling(what I wanted to do was impossible without massive overhead otherwise)

**Comment by AlexIIL** [comment]
Oh so its not just me then :) But I'm going to try and step through the code at some point, and really find out what's happening. (It also happens for me if a method that was called had a compile error but eclipse still exported it)

**Comment by AlexIIL** [comment]
Huh. After stepping through the code it seems like this happens because forge exports minecraft's jar file without line information or anything so it crashes doing `stacktraceelement2.getFileName().equals(s1.getFileName())`

**Comment by iame6162013** [comment]
I think it's because of an error outside of java so the stack trace is wrong but that's what I think. how do you get this error btw?

**Comment by AlexIIL** [comment]
Sorry for not commenting ages ago, but it seems to be related to forge gradle not exporting line numbers (specifically MinecraftForge/ForgeGradle#254 )
