### ISSUE TITLE
Crash when adding pipe

### ISSUE THREAD

**Issue by maqjav** [AlexIIL/Buildcraft_1.8_Issues#51]
Hello, I'm testing the last alpha-3 and I got the next stacktrace when I tried to add a kinetic iron pipe on top of a redstone engine. 

Now I cannot get in my world again, I get this instant crash.

``` java
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  CCCDeobfPlugin (unknown)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 25/10/15 19:35
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
    at net.minecraft.client.renderer.block.model.BakedQuad.makeVertexDataSingle(BakedQuad.java:92)
    at net.minecraft.client.renderer.block.model.BakedQuad.getVertexDataSingle(BakedQuad.java:76)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusionQuads(BlockModelRenderer.java:268)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusion(BlockModelRenderer.java:126)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:61)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:50)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:250)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.client.renderer.block.model.BakedQuad.makeVertexDataSingle(BakedQuad.java:92)
    at net.minecraft.client.renderer.block.model.BakedQuad.getVertexDataSingle(BakedQuad.java:76)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusionQuads(BlockModelRenderer.java:268)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusion(BlockModelRenderer.java:126)

-- Block model being tesselated --
Details:
    Block: buildcraft|transport:pipeBlock[connected_down=true,connected_east=true,connected_north=true,connected_south=true,connected_up=true,connected_west=true,pipe_data=0]
    Block location: World: (-753,72,276), Chunk: (at 15,4,4 in -48,17; contains blocks -768,0,272 to -753,255,287), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
    Using AO: true
Stacktrace:
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:61)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:50)

-- Block being tesselated --
Details:
    Block type: ID #657 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-753,72,276), Chunk: (at 15,4,4 in -48,17; contains blocks -768,0,272 to -753,255,287), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
Stacktrace:
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['maqjav'/310, l='MpServer', x=-754,61, y=71,00, z=275,47]]
    Chunk stats: MultiplayerChunkCache: 289, 289
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: 188,00,64,00,269,00 - World: (188,64,269), Chunk: (at 12,4,13 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 9719081 game time, 9766275 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 67 total; [EntityLaser['desconocido'/1408, l='MpServer', x=2147483647,00, y=2147483647,00, z=2147483647,00], EntityLaser['desconocido'/1409, l='MpServer', x=2147483647,00, y=2147483647,00, z=2147483647,00], EntityLaser['desconocido'/1410, l='MpServer', x=2147483647,00, y=2147483647,00, z=2147483647,00], EntityLaser['desconocido'/1411, l='MpServer', x=2147483647,00, y=2147483647,00, z=2147483647,00], EntityLaser['desconocido'/1412, l='MpServer', x=2147483647,00, y=2147483647,00, z=2147483647,00], EntityLaser['desconocido'/1413, l='MpServer', x=2147483647,00, y=2147483647,00, z=2147483647,00], EntityLaser['desconocido'/1414, l='MpServer', x=2147483647,00, y=2147483647,00, z=2147483647,00], EntityLaser['desconocido'/1415, l='MpServer', x=2147483647,00, y=2147483647,00, z=2147483647,00], EntityWitch['Bruja'/413, l='MpServer', x=-762,50, y=26,02, z=320,50], EntityZombie['Zombi'/305, l='MpServer', x=-740,50, y=10,00, z=273,50], EntityItem['item.item.seeds'/306, l='MpServer', x=-748,13, y=70,00, z=273,09], EntityCreeper['Creeper'/307, l='MpServer', x=-732,34, y=69,00, z=258,44], EntityZombie['Zombi'/308, l='MpServer', x=-733,50, y=33,00, z=276,50], EntityBat['Murciélago'/309, l='MpServer', x=-751,63, y=42,10, z=290,75], EntitySkeleton['Esqueleto'/311, l='MpServer', x=-759,50, y=58,00, z=296,06], EntityItem['item.tile.dirt.default'/312, l='MpServer', x=-783,63, y=63,00, z=268,88], EntityItem['item.tile.dirt.default'/313, l='MpServer', x=-783,25, y=62,00, z=265,28], EntityItem['item.tile.dirt.default'/314, l='MpServer', x=-782,69, y=63,00, z=266,53], EntitySkeleton['Esqueleto'/315, l='MpServer', x=-763,75, y=69,00, z=313,78], EntityZombie['Zombi'/316, l='MpServer', x=-768,50, y=35,00, z=312,50], EntityZombie['Zombi'/317, l='MpServer', x=-769,94, y=35,00, z=316,16], EntityZombie['Zombi'/318, l='MpServer', x=-775,25, y=69,00, z=318,81], EntityItem['item.tile.dirt.default'/319, l='MpServer', x=-786,88, y=63,00, z=268,13], EntityItem['item.tile.dirt.default'/320, l='MpServer', x=-785,78, y=63,00, z=268,53], EntityItem['item.tile.dirt.default'/321, l='MpServer', x=-784,91, y=63,00, z=265,84], EntityItem['item.tile.dirt.default'/322, l='MpServer', x=-785,13, y=63,00, z=267,56], EntityItem['item.tile.dirt.default'/323, l='MpServer', x=-784,88, y=61,00, z=265,59], EntitySpider['Araña'/324, l='MpServer', x=-778,72, y=58,02, z=246,69], EntityZombie['Zombi'/325, l='MpServer', x=-722,66, y=70,00, z=296,34], EntityPig['Cerdo'/326, l='MpServer', x=-742,19, y=70,00, z=318,00], EntityBat['Murciélago'/327, l='MpServer', x=-782,88, y=58,02, z=247,44], EntitySpider['Araña'/328, l='MpServer', x=-723,09, y=70,00, z=240,66], EntityBat['Murciélago'/329, l='MpServer', x=-763,31, y=18,97, z=331,44], EntitySkeleton['Esqueleto'/330, l='MpServer', x=-778,50, y=35,00, z=321,50], EntityCow['Vaca'/331, l='MpServer', x=-742,00, y=70,00, z=326,16], EntityItem['item.tile.dirt.default'/332, l='MpServer', x=-787,75, y=65,00, z=227,69], EntityItem['item.tile.dirt.default'/333, l='MpServer', x=-789,78, y=65,00, z=225,72], EntitySpider['Araña'/334, l='MpServer', x=-717,50, y=70,00, z=242,50], EntityPig['Cerdo'/335, l='MpServer', x=-713,84, y=70,00, z=307,31], EntityPig['Cerdo'/336, l='MpServer', x=-715,31, y=70,00, z=306,44], EntityPig['Cerdo'/337, l='MpServer', x=-726,47, y=61,00, z=335,53], EntityMinecartEmpty['entity.MinecartRideable.name'/338, l='MpServer', x=-820,53, y=6,06, z=275,50], EntityPig['Cerdo'/339, l='MpServer', x=-772,00, y=68,00, z=343,09], EntityZombie['Zombi'/340, l='MpServer', x=-821,50, y=12,00, z=298,50], EntityCreeper['Creeper'/341, l='MpServer', x=-691,13, y=68,00, z=258,72], EntityPig['Cerdo'/342, l='MpServer', x=-737,19, y=70,00, z=337,63], EntitySheep['Oveja'/343, l='MpServer', x=-746,47, y=69,00, z=339,34], EntitySkeleton['Esqueleto'/344, l='MpServer', x=-808,50, y=17,00, z=225,50], EntityPig['Cerdo'/345, l='MpServer', x=-723,13, y=69,00, z=342,44], EntityPig['Cerdo'/346, l='MpServer', x=-822,50, y=68,00, z=334,59], EntitySkeleton['Esqueleto'/347, l='MpServer', x=-753,50, y=68,00, z=199,50], EntityCow['Vaca'/348, l='MpServer', x=-688,31, y=68,00, z=328,25], EntityPig['Cerdo'/349, l='MpServer', x=-719,88, y=69,00, z=338,78], EntitySpider['Araña'/350, l='MpServer', x=-761,53, y=67,00, z=353,69], EntitySpider['Araña'/351, l='MpServer', x=-678,13, y=68,00, z=261,09], EntitySpider['Araña'/352, l='MpServer', x=-675,50, y=68,00, z=264,50], EntityCow['Vaca'/355, l='MpServer', x=-688,47, y=66,00, z=350,56], EntityCow['Vaca'/361, l='MpServer', x=-686,19, y=63,00, z=338,16], EntityCow['Vaca'/363, l='MpServer', x=-676,50, y=65,00, z=337,84], EntityPlayerSP['maqjav'/310, l='MpServer', x=-754,61, y=71,00, z=275,47], EntityCreeper['Creeper'/372, l='MpServer', x=-724,50, y=46,00, z=328,50], EntityCreeper['Creeper'/373, l='MpServer', x=-726,22, y=46,00, z=327,72], EntitySpider['Araña'/374, l='MpServer', x=-680,50, y=72,00, z=199,50], EntityLaser['desconocido'/1404, l='MpServer', x=2147483647,00, y=2147483647,00, z=2147483647,00], EntityLaser['desconocido'/1405, l='MpServer', x=2147483647,00, y=2147483647,00, z=2147483647,00], EntityLaser['desconocido'/1406, l='MpServer', x=2147483647,00, y=2147483647,00, z=2147483647,00], EntityLaser['desconocido'/1407, l='MpServer', x=2147483647,00, y=2147483647,00, z=2147483647,00]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:407)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2503)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 309461632 bytes (295 MB) / 808128512 bytes (770 MB) up to 3207856128 bytes (3059 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1521 Optifine OptiFine_1.8_HD_U_D5 15 mods loaded, 15 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1521.jar) 
    UCHIJAAAA   Forge{11.14.3.1521} [Minecraft Forge] (forge-1.8-11.14.3.1521.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
    UCHIJAAAA   BuildCraft|Core{7.0.0-wip} [BuildCraft] (buildcraft-ALPHA-3.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.0.0-wip} [BC Transport] (buildcraft-ALPHA-3.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.0.0-wip} [BC Factory] (buildcraft-ALPHA-3.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.0.0-wip} [BC Silicon] (buildcraft-ALPHA-3.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.0.0-wip} [BC Robotics] (buildcraft-ALPHA-3.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.0.0-wip} [BC Energy] (buildcraft-ALPHA-3.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.0.0-wip} [BC Builders] (buildcraft-ALPHA-3.jar) 
    UCHIJAAAA   journeymap{5.1.1b7} [JourneyMap] (journeymap-1.8-5.1.1b7-unlimited.jar) 
    UCHIJAAAA   chunkbase_slimemod_ssp{2.1} [Slime Mod (SSP)] (SlimeModSSP-1.8-2.1.jar) 
    UCHIJAAAA   Waila{1.6.0_B1} [Waila] (Waila-1.6.0_B1_1.8.1.jar) 
    Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)

NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Launched Version: 1.8-forge1.8-11.14.3.1521
    LWJGL: 2.9.1
    OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: [JSTR_Universal_1.7.x.zip, John Smith Legacy JSC v1.1.20.zip, Musica.zip]
    Current Language: Español (España)
    Profiler Position: N/A (disabled)
```

**Comment by AlexIIL** [comment]
Can you put your entire forge-latest log into a gist please?

**Comment by AlexIIL** [comment]
(I can't reproduce it atm)

**Comment by AlexIIL** [comment]
Also, were there any other pipes or blocks around the pipe or engine? (If its easier you could always send me your world)

**Comment by maqjav** [comment]
Hello AlexIIL. The engine was on top of a dirt block, and right on top of the engine I added the pipe (air around the engine and the pipe in the rest of sides). I will send you the forge log later, I'm at work right now.

Thanks for your help.

**Comment by maqjav** [comment]
Hello again, here is the latest.log content. 
I deleted the previous one, login my world and wait for the crash. I see a lot of FileNotFoundExceptions with textures, I don't know if this can produce the issue.

Here is the link to my gist: https://gist.github.com/maqjav/f758f9b8aa9bade763f4

**Comment by maqjav** [comment]
Hello AlexIIL, I found the issue!
I had optifine installed and it was giving problems with Buildcraft. I found in your forums that it's not compatible with BC (my fault!).

Sorry for wasting your time. I will keep testing the mod, but this time without other mods.

Deleting optifine fixes the problem and everything works just fine.

Thanks again.
