### ISSUE TITLE
Buildcraft 1.8.8 crash on server

### ISSUE THREAD

**Issue by grannyte** [AlexIIL/Buildcraft_1.8_Issues#77]
i'm getting a crash on a server to test buildcraf on 1.8.8

[22:14:32] [Server thread/ERROR] [FML/]: Fatal errors were detected during the transition from INITIALIZATION to POSTINITIALIZATION. Loading cannot continue
[22:14:32] [Server thread/ERROR] [FML/]: 
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.18} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{8.0.99.99} [Forge Mod Loader](forge-1.8.8-11.15.0.1635-1.8.8-universal.jar) 
    UCHI    Forge{11.15.0.1635} [Minecraft Forge](forge-1.8.8-11.15.0.1635-1.8.8-universal.jar) 
    UCHI    BiomesOPlenty{3.0.0} [Biomes O' Plenty](BiomesOPlenty-1.8.8-3.0.0.1530-universal.jar) 
    UCHE    BuildCraft|Core{7.2.0pre4} [BuildCraft](buildcraft-7.2.0pre4.jar) 
    UCHE    BuildCraft|Transport{7.2.0pre4} [BC Transport](buildcraft-7.2.0pre4.jar) 
    UCHE    BuildCraft|Factory{7.2.0pre4} [BC Factory](buildcraft-7.2.0pre4.jar) 
    UCHE    BuildCraft|Silicon{7.2.0pre4} [BC Silicon](buildcraft-7.2.0pre4.jar) 
    UCHE    BuildCraft|Robotics{7.2.0pre4} [BC Robotics](buildcraft-7.2.0pre4.jar) 
    UCHE    BuildCraft|Energy{7.2.0pre4} [BC Energy](buildcraft-7.2.0pre4.jar) 
    UCHE    BuildCraft|Builders{7.2.0pre4} [BC Builders](buildcraft-7.2.0pre4.jar) 
    UCHI    Dynmap{2.1-29} [Dynmap](Dynmap-2.1-forge-1.8.0.jar) 
    UCHI    AS_Ruins{15.5} [Ruins Spawning System](Ruins-1.8.8.jar) 
[22:14:32] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[22:14:32] [Server thread/ERROR] [FML/]: Caught exception from BuildCraft|Core
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/TextureAtlasSprite
    at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_45]
    at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_45]
    at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:1.8.0_45]
    at java.lang.Class.getMethods(Unknown Source) ~[?:1.8.0_45]
    at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:60) ~[EventBus.class:?]
    at buildcraft.core.statements.BCStatement.<init>(BCStatement.java:37) ~[BCStatement.class:?]
    at buildcraft.builders.statements.ActionFiller.<init>(ActionFiller.java:43) ~[ActionFiller.class:?]
    at buildcraft.builders.statements.ActionFiller.resetMap(ActionFiller.java:32) ~[ActionFiller.class:?]
    at buildcraft.BuildCraftCore.init(BuildCraftCore.java:422) ~[BuildCraftCore.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:559) ~[forge-1.8.8-11.15.0.1635-1.8.8-universal.jar:?]
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.8.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.8.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.8.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.8.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.8.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) ~[forge-1.8.8-11.15.0.1635-1.8.8-universal.jar:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) ~[forge-1.8.8-11.15.0.1635-1.8.8-universal.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.8.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.8.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.8.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.8.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.8.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:729) [Loader.class:?]
    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:205) [ko.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.TextureAtlasSprite
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    ... 40 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@37e4d7bb from coremod FMLCorePlugin
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234) ~[forge-1.8.8-11.15.0.1635-1.8.8-universal.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    ... 40 more
Caused by: java.lang.RuntimeException: Attempted to load class bmi for invalid side SERVER
    at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:49) ~[forge-1.8.8-11.15.0.1635-1.8.8-universal.jar:?]
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230) ~[forge-1.8.8-11.15.0.1635-1.8.8-universal.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    ... 40 more
[22:14:34] [Server thread/WARN] [FML/]: Can't revert to frozen GameData state without freezing first.

**Comment by AEnterprise** [comment]
could you use gist or pastebin for crashlogs instead of just dumping them in the description, that would make reading them much easier

**Comment by grannyte** [comment]
Here it's on pastebin
http://pastebin.com/az8XxYAD

**Comment by AlexIIL** [comment]
Thanks! Sorry I missed this one before, fortunately its not too difficult to fix.

**Comment by grannyte** [comment]
I compiled the dev version for my server seem to work fine thanks
